/// Generic Dimensions
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_MEDIUM_1 = 10.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;


const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_1X = 16.0;
const TEXT_REGULAR_2X = 18.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 28.0;
const TEXT_SMALL = 12.0;
const TEXT_XSMALL = 10.0;
const TEXT_BIG = 32.0;
const TEXT_BIG_1X = 48.0;
const TEXT_BIG_2X = 64.0;

///specified
const CUSTOM_BUTTON_BORDER_WIDTH = 2.0;
const CUSTOM_BUTTON_HEIGHT = 50.0;
const CUSTOM_BUTTON_RADIUS = 5.0;
const HI_TXT_FONT_SIZE = 30.0;
const PIN_PUT_TEXT_SIZE = 21.0;
const PIN_THEME_BORDER_RADIUS = 5.0;

const GET_OTP_BUTTON_WIDTH = 20.0;
const GET_OTP_BUTTON_HEIDHT = 40.0;
const VERITY_BUTTON_WIDTH = 115.0;
const VERITY_BUTTON_HEIGHT = 40.0;

const CHECK_BOX_SIZE_WIDTH = 20.0;
const CHECK_BOX_SIZE_HEIGHT = 20.0;

const MOMENT_DESC_IMAGE_WIDTH = 150.0;
const MOMENT_DESC_IMAGE_HEIGHT = 170.0;

const ACTIVE_NOW_CHAT_LIST_SECTION_HEIGHT = 100.0;
const ACTIVE_NOW_CHAT_ITEM_WIDTH = 75.0;

const ACTIVE_NOW_CHAT_ITEM_PROFILE_RADIUS = 30.0;
const ACTIVE_STATUS_CIRCLE_SIZE = 18.0;

const CHAT_HISTORY_ITEM_PROFILE_RADIUS = 25.0;
const CHAT_HISTORY_CARD_HEIGHT = 85.0;